"""add_kis_customer_id

Revision ID: 8db656abf9d7
Revises: 04a02718b704
Create Date: 2026-05-11 15:17:08.502080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db656abf9d7'
down_revision: Union[str, Sequence[str], None] = '04a02718b704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kis_customer_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kis_customer_id')
    # ### end Alembic commands ###
